import type { TClassProperties, Textbox } from "fabric"
import { ComponentType } from "~/constants/enum"
import type { FontWeight, TextAlign } from "~/constants/enum/style"
export type TextboxProps = Partial<TClassProperties<Textbox>> & {type: ComponentType.TextBox, id?: string}

export const TextCanvasStyle: TextboxProps = {
  fontWeight: 'normal' as FontWeight,
  shadow: null,
  textAlign: 'left' as TextAlign,
  fontSize: 16,
  fontFamily: "Arial",
  fontStyle: "normal",
  lineHeight: 1.5,
  text: "Hello World",
  charSpacing: 0,
  // styles: [],
  path: null,
  pathStartOffset: 0,
  pathSide: "left",
  pathAlign: "baseline",
  underline: false,
  overline: false,
  linethrough: false,
  textBackgroundColor: "transparent",
  direction: "ltr",
  minWidth: 20,
  splitByGrapheme: true,
  originX: "left",
  originY: "top",
  left: 125.5,
  top: 97,
  width: 100,
  height: 18.08,
  fill: "#181818",
  stroke: null,
  strokeWidth: 1,
  strokeDashArray: null,
  strokeLineCap: "butt",
  strokeDashOffset: 0,
  strokeLineJoin: "miter",
  strokeUniform: false,
  strokeMiterLimit: 4,
  scaleX: 1,
  scaleY: 1,
  angle: 0,
  flipX: false,
  flipY: false,
  opacity: 1,
  visible: true,
  backgroundColor: "",
  fillRule: "nonzero",
  paintFirst: "fill",
  skewX: 0,
  skewY: 0,
  type: ComponentType.TextBox,
}
export const textBlock = {
  type: ComponentType.TextBox as ComponentType.TextBox,
  id: '',
  isLock: false,
  icon: 'TextIcon',
  name: 'Text',
  canvasStyle: {
    ...TextCanvasStyle,
  },
}